### ISSUE TITLE
Add homebrew formula for txtorcon

### ISSUE THREAD

**Issue by sammyshj** [meejah/txtorcon#112]
A homebrew formula can be added for txtorcon. This will help users with Homebrew install txtorcon just by typing, `brew install txtorcon`

**Comment by sammyshj** [comment]
I am currently working on this issue

**Comment by sammyshj** [comment]
Currently I have created a PR in the homebrew repo to add txtorcon-0.12.0 as a homebrew formula.
The PR can be seen at https://github.com/Homebrew/homebrew/pull/38932

**Comment by sammyshj** [comment]
I tried creating a homebrew formula for stem too previously but it looks like Homebrew does not package Python libraries. The conversation about stem can be seen at https://github.com/Homebrew/homebrew/pull/38911
Hence, this issue can be closed.

**Comment by meejah** [comment]
I see, so the recommendation is to just use "pip install txtorcon" on Homebrew, is that right?

Would it make sense to add a note somewhere in txtorcon's docs that OS X + Homebrew works fine?

**Comment by meejah** [comment]
BTW, thanks for digging into this.

**Comment by sammyshj** [comment]
The best method to get txtorcon for OSX is to follow one of the following methods:
`sudo easy_install txtorcon`
`sudo pip install txtorcon`

Yes, I will add a note on the txtorcon's docs about the same and create a new PR for it :)

**Comment by meejah** [comment]
No, please don't recommend using sudo. The instructions should do things in a virtualenv.

**Comment by sammyshj** [comment]
The discussion about the docs is continued in #113
