### ISSUE TITLE
Add OSX installation instructions for txtorcon

### ISSUE THREAD

**Issue by sammyshj** [meejah/txtorcon#113]
Txtorcon can be installed on OSX by following one of the methods given below:
`sudo easy_install txtorcon`
`sudo pip install txtorcon`

The above instructions need to be added to txtorcon's docs

**Comment by meejah** [comment]
Oops, should have commented here. Don't use ``sudo``, make any examples use a virtualenv instead please.

**Comment by sammyshj** [comment]
Thanks for pointing that out. I will take care of that :)
