### ISSUE TITLE
Rectify IAddress and authenticated hidden-services

### ISSUE THREAD

**Issue by david415** [meejah/txtorcon#131]
onion not showing up in the str repr for onion service addr object... but the port shows up.

**Comment by meejah** [comment]
This is a consequence of the stealth-auth stuff on master, and the "XXX" comments around endpoints.py line 460 -- stealth-authenticated hidden-services do not have "a" onion URI, but N onion URIs.

Still trying to figure out this API precisely... :/

**Comment by meejah** [comment]
I'm trying to avoid having like 6 different HiddenService classes:

 - "normal" hidden-services (have a 'directory' on disk)
 - authenticated hidden-services (add an authentication token)
 - stealth-authenticated hidden-services (different onion address per-user, and a token per user)
 - ephemeral hidden-services (no directory, adds a private-key, different API to add to Tor, no enumeration possible)

So, the issues are:

 - API to get "the onion address" probably needs to be a method (that takes a client tag)
 - need some notion of "serialization" (i.e. "normal" HSes get saved to Tor via SETCONF and loaded via GETCONF or torrc + reading directory, "ephemeral" get saved via ADD_ONION/DEL_ONION and can't be loaded)
 - all the @clasmethods to create a HiddenServiceEndpoint need to take a private_key **or** directory (but not both) "or something" to determine ephemeral vs normal HSes
 - I would like to ideally avoid having EphemeralHiddenService, StealthHiddenService, and HiddenService classes (which is one way around the above).
 - bikeshed: should they all be OnionServices if the API is changing anyway?

**Comment by meejah** [comment]
For now, I've put in a workaround so that you get the first hostname if there are multiples (so, if you're using "normal" hidden-services, it works again).

**Comment by meejah** [comment]
I believe the new Onion API addresses this
