### ISSUE TITLE
Fix compatibility with Twisted 15.5.0

### ISSUE THREAD

**Issue by hellais** [meejah/txtorcon#146]
As noted in the Twisted changelog (https://github.com/twisted/twisted/blob/3df4e95b63f00eb92005301de1594218fc02e0cb/twisted/topfiles/NEWS#L62) and highlighted by ooni-probe continuous integration test (https://travis-ci.org/TheTorProject/ooni-probe/jobs/93784032) `IStreamClientEndpointStringParser` is deprecated in Twisted 15.5.0.
They recommend using `twisted.internet.interfaces.IStreamClientEndpointStringParserWithReactor`.

More details on the trac of twisted:

* http://twistedmatrix.com/trac/ticket/8094

* http://twistedmatrix.com/trac/ticket/5069

From the looks of it, it doesn't seem to be a complicated fix as the APIs seem mainly compatible one with the other, you just need to pass in the extra reactor argument.

**Comment by meejah** [comment]
On master, and in 0.14.2
