### ISSUE TITLE
Fallback to password when cookie isn't readable

### ISSUE THREAD

**Issue by coffeemakr** [meejah/txtorcon#149]
In `TorControlProtocol._do_authenticate` when COOKIE authentication is enabled it is always tries to read the cookie. If this fails (for example because the running process doesn't have access rights) an uncatched IOError is raised.

Wouldn't it be better to catch the exception and try password authentication before failing?

Regards

**Comment by meejah** [comment]
Yes, probably that would be better.

Examining the code probably the best behavior is to try cookie/safecookie if they're available, but upon errors try password auth IFF it's available *and* we have a ``.password_function``.

**Comment by meejah** [comment]
This is merged in #150; closing. Thanks @coffeemakr!
