### ISSUE TITLE
Evaluate replacement of python-ipaddr with python-ipaddress

### ISSUE THREAD

**Issue by evilaliv3** [meejah/txtorcon#153]
Starting from version 3.3 python will include a library dealing with ip addresses: [ipaddress](https://docs.python.org/3/library/ipaddress.html)

This library has been already ported to python 2.7 and packaged for the upcoming debian stretch and ubuntu xenial (the latter will include by default and only python 3 so that it wont require neither python-ipaddress)

Given that the API is the same It would be valuable to evaluate the replacement of ipaddr with this new library.

This would also simplify integration of txtorcon in programs that include both txtorcon and cryptography as cryptography has already opted in this direction: https://pypi.python.org/pypi/ipaddress

**Comment by meejah** [comment]
This sounds useful.

**Comment by meejah** [comment]
(Not strictly python3, but I guess related). Thanks for the pointer :)

**Comment by meejah** [comment]
Implemented in master
