### ISSUE TITLE
txsocksx not supported for python3

### ISSUE THREAD

**Issue by akash-47** [meejah/txtorcon#162]
see https://github.com/habnabit/txsocksx/issues/16
Can't pip install txsocksx for python 3.4-3.5
While there are no issues encountered for python2.

Terminal output:
error in txsocksx setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; 'int' object is not iterable

**Comment by meejah** [comment]
This will mean no client-side support (e.g. TorClientEndpoint) for Python3 users until txsocksx is fixed. The only real solution here is to fix txsocksx (unless there's another quality Twisted SOCKS library I'm not aware of ;) )

**Comment by david415** [comment]
ok... let's just write a SOCKS 5 client for txtorcon... or adapt a good enough twisted implementation. I think there are various good ones already written by i forget who exactly, perhaps Yawning or Linus from Tor Project. I also remember seeing some code in a twistedmatrix trac ticket.

**Comment by meejah** [comment]
Already done: https://github.com/meejah/txtorcon/blob/release-1.x/txtorcon/socks.py
Probably needs more tests...

**Comment by meejah** [comment]
Now implemented in `socks.py`

**Comment by mvrozanti** [comment]
uhm... Why is this closed?
