### ISSUE TITLE
Listwrapper - no __setslice__ attribute

### ISSUE THREAD

**Issue by akash-47** [meejah/txtorcon#163]
python 3 lists have no **setslice** attribute. (torconfig.py line 656)
Use six for getting around this ?

**Comment by meejah** [comment]
Possibly, yes. I haven't looked into this very far though.

In many ways, TorConfig is kind of "too magic" already -- but supporting Python3 is good.

The context here is that longer-term I'd like to replace/upgrade/change TorConfig to be more explicit (or have a different object that's not-magic and leave TorConfig around). Having to wrap all the lists etc "just" to trigger the "dirty" notification has kind of gotten out of control ;) and so I'd also be open to a totally new API, or a nicer way to do it.

Thanks for the report!

**Comment by meejah** [comment]
This issue is fixed (we only set __setslice__ for py2).
