### ISSUE TITLE
Tor client endpoint should be able to use UNIX domain sockets for it's SOCKS connection

### ISSUE THREAD

**Issue by david415** [meejah/txtorcon#181]
Ideally the tor client endpoint should be able to connect to a UNIX domain socket if that's tor's SOCKS port. I'm actually not so concerned about how the endpoint parser will deal with this... because for the tahoe tor integration use case we really do not need to use the endpoint parser; we just need an api that works.

**Comment by meejah** [comment]
The `release-1.x` branch is probably the best place to start -- as I'm moving away from txsocksx ("because Python3") anyway and have a SOCKS implementation in that branch that also supports the two Tor custom opcodes. I'm not sure if txsocksx supports Unix domain sockets anyway.

**Comment by warner** [comment]
[Foolscap#265](https://foolscap.lothar.com/trac/ticket/265) is where we need this. It looked like there might be a way to hack this into `txtorcon.TorClientEndpoint` (by abusing the private `_proxy_endpoint_generator=`), but I don't want to do something so obviously fragile as that.

Maybe a `TorClientEndpoint` constructor that just takes an endpoint for the SOCKS port as an argument? I don't remember how reusable endpoints are.. if for some reason it's not legal to call `.connect()` multiple times, then we could pass in a no-argument function that returns endpoints on demand..

**Comment by david415** [comment]
@warner we worked on it here: https://github.com/meejah/txtorcon/pull/182

**Comment by meejah** [comment]
Also, FWIW, the API in #182 is (now) the same as currently exists in `release-1.x` (where this already works).

**Comment by meejah** [comment]
See https://github.com/meejah/txtorcon/pull/183

**Comment by meejah** [comment]
in 0.16.1
