### ISSUE TITLE
Missing note about necessary libgeoip-dev dependency on GNU/Linux

### ISSUE THREAD

**Issue by lwm** [meejah/txtorcon#194]
Hio, cool project. I was trying to get a local copy up and running and ran into the following:

``` bash
$ make venv
$ pip install -r requirments.txt
... # success!
$ pip install -r dev-requirements.txt
...  # lots of noise
py_GeoIP.c:23:19: fatal error: GeoIP.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
```

This was solved with:

``` bash
    $ sudo apt-get install -y libgeoip-dev
```

I couldn't find it listed in the documentation. 

Where could I add it? I'd submit a PR.

**Comment by meejah** [comment]
I would add this to the `README.rst`.

It would also be great if you could take a look at the upcoming "release-1.x" documentation and see if they make sense (especially if you're a new user!). They are available here: https://txtorcon.readthedocs.io/en/release-1.x/

**Comment by lwm** [comment]
Yeah, totally new here. I'll take a look and add some changes in this PR. Thanks.

**Comment by lwm** [comment]
Regarding the new docs, you're definitely going in the right direction. I wasn't able to really grok what `txtorcon` was for, or get an example running from the old docs, but after reviewing [the new introduction](https://txtorcon.readthedocs.io/en/release-1.x/introduction.html#introduction), I was up and running with a better idea.

I did just run into [the walkthrough](https://txtorcon.readthedocs.io/en/latest/walkthrough.html) in latest which is also quite useful if you're porting some of that over.
