### ISSUE TITLE
my problem or old code?

### ISSUE THREAD

**Issue by cryptid11** [meejah/txtorcon#197]
https://txtorcon.readthedocs.io/en/latest/examples.html#hello-darkweb-py this doen't seems to work anymore or it's just me?

**Comment by meejah** [comment]
Works for me with current master and latest release. What output do you see?

**Comment by cryptid11** [comment]
I do port forwarding and this is output:

```
Connecting to directory server
Finishing handshake with directory server
Establishing an encrypted directory connection
Asking for networkstatus consensus
Loading networkstatus consensus
Loading authority key certs
Asking for relay descriptors
Loading relay descriptors
...
Loading relay descriptors
Connecting to the Tor network
Establishing a Tor circuit
Done
Waiting for descriptor upload...
At least one descriptor uploaded.
TorOnionAddress('lr54xoxlrptk4bp3.onion', 4500)
```
and this is what I see on torpage:

> No Such Resource
> No such child resource.

Sorry I'm a bit forgetful, for sure will be for some obvious distraction but I can't understand what is it!

**Comment by meejah** [comment]
Ah, hmm, okay -- so the site comes up and is "kind-of" working, but doesn't give serve the page at the expected place ... okay

**Comment by meejah** [comment]
Is this more-clear? (Also: it works :)
https://github.com/meejah/txtorcon/pull/198
