### ISSUE TITLE
Not installing on Python 3 without ipaddress

### ISSUE THREAD

**Issue by jluttine** [meejah/txtorcon#247]
README states: "depends on Twisted, Automat, (and the ipaddress backport for non Python 3)". So, ipaddress shouldn't be required on Python 3? Still, installing it on Python 3 fails because of missing ipaddress:

```
Collecting ipaddress>=1.0.16 (from txtorcon==0.19.3)
  Could not find a version that satisfies the requirement ipaddress>=1.0.16 (from txtorcon==0.19.3) (from versions: )
No matching distribution found for ipaddress>=1.0.16 (from txtorcon==0.19.3)
```

**Comment by meejah** [comment]
I think this is probably just a `setup.py` problem; we should use the new qualifiers to exclude `ipaddress` from being a requirement for Py3

**Comment by hlieberman** [comment]
Just ran into this during the Debian packaging of an unrelated package that depends on txtorcon.  Can you take a look at this, @meejah?
