### ISSUE TITLE
test_return_geoip_object fails as new geoip tests if database is not corrupt

### ISSUE THREAD

**Issue by irl** [meejah/txtorcon#250]
The new test can be seen at:

http://sources.debian.net/src/geoip/1.6.11-2/libGeoIP/GeoIP.c/#L1202

This didn't exist a couple of minor releases ago, but the test will now fail as it's being given an empty file, not a valid database.

**Comment by jluttine** [comment]
I'm packaging txtorcon for a distro and this causes problems. Would like to see it solved or is there a workaround? Is it safe to just skip the failing test?

**Comment by irl** [comment]
@jluttine You can just skip the failing test. The problem is that the GeoIP library now validates that the database is valid before giving you an object back but in the test case, it is not valid, so will always fail. A fixed test case would provide a valid database.

**Comment by irl** [comment]
This test is still broken in 19.0.0.
