### ISSUE TITLE
on_disconnect should be replaced with proper API

### ISSUE THREAD

**Issue by meejah** [meejah/txtorcon#284]
This never should have been a public API. Oh well, it is.

**Comment by meejah** [comment]
The immediate bug (spurious "Unhandled error in Deferred") is fixed on trunk already, but there should be something like "when_disconnected()" that returns a new Deferred for each caller using the `SingleObserver()` object and `on_disconnect` should be deprecated.

**Comment by glowatsk** [comment]
Hey I am trying to see if I can figure this out.

We want a new method
`on_disconnect(self):`

But I am unsure of what SingleObserver() is referencing, could you point me to where I can find this / read about this.

Then we can return the call to the code below:
```
if not self.on_disconnect.called and self.on_disconnect.callbacks:
            if reason.check(ConnectionDone):
                self.on_disconnect.callback(self)
            else:
                self.on_disconnect.errback(reason)
        self.on_disconnect = None
```

Let me know if I am understanding this correctly.

Thank You,

**Comment by meejah** [comment]
Hi @glowatsk!

Yes, nearly! So, we can't re-use `on_disconnect` because of backwards-compatibility. So I would introduce a new method called `when_disconnected()` or so. The `SingleObserver` is this utility: https://github.com/meejah/txtorcon/blob/master/txtorcon/util.py#L473 (and we can then deprecate `.on_disconnect` -- but also it might be used internally already).

So, you can add `self._disconnected = SingleObserver()`, approximately, and `.fire(...)` it when we disconnect (so you shouldn't need the outer "if" check in the code you quoted because `SingleObserver` remembers if it was already fired).

**Comment by meejah** [comment]
Now on master
