### ISSUE TITLE
build_timeout_circuit should return reason + remote_reason on failure

### ISSUE THREAD

**Issue by meejah** [meejah/txtorcon#285]
If a circuit build fails (i.e. circuit_closed or circuit_failed is called before when_built is signaled) then the Deferred returned should get an errback with the reason + remote_reason strings.

**Comment by david415** [comment]
i tried to get this working here: https://github.com/meejah/txtorcon/pull/287

made some progress but not done. sloppy PR intended for review only.

**Comment by meejah** [comment]
Now implemented
