### ISSUE TITLE
make an asyncio aiohttp example

### ISSUE THREAD

**Issue by meejah** [meejah/txtorcon#289]
As per discussion on #twisted with @markrwilliams it should be possible to make twisted and asyncio play nicely together. There should be an example of this now that txtorcon supports Python3.

The "most interesting" would probably be "make a client-type request via Tor" using the aiohttp requests APIs. A "really cool" example would be running an aiohttp web server behind a v3 Onion service...

**Comment by meejah** [comment]
This is done, see https://github.com/meejah/txtorcon/blob/master/examples/web_onion_service_aiohttp.py

**Comment by kamikaze** [comment]
can we get rid for twisted? Looks too expensive for a simple example

**Comment by meejah** [comment]
No. txtorcon always needs twisted, and that's kind of the point of the example anyway.
