### ISSUE TITLE
TCPHiddenServiceEndpointParser.parseStreamServer drops privateKey argument on the floor

### ISSUE THREAD

**Issue by exarkun** [meejah/txtorcon#314]
It looks like you're supposed to be able to supply a privateKey to the `onion:...` endpoint server string parser.  And you can supply it - but it's not used for anything (apart from checking for conflicting with a `hiddenServiceDir` value).  The net result is that when passing a `privateKey`, you always get a newly allocated key from the Tor daemon, I think.

**Comment by exarkun** [comment]
I tried to use TCPHiddenServiceEndpointParser to implement another endpoint that works with a privateKeyPath instead.  I wanted to do this to avoid duplicating the control port handling code in TCPHiddenServiceEndpointParser (and some other minor logic).  The `privateKey` handling seems to preclude this possibility though, at least for now.

**Comment by meejah** [comment]
This appears to have been fixed in 89062746cd245ffda4788b5b4696d4469514e45c (which was first released in `v18.2.0` according to a git incantation).
