### ISSUE TITLE
Build error with python-2.7

### ISSUE THREAD

**Issue by yurivict** [meejah/txtorcon#321]
```
writing byte-compilation script '/tmp/tmpmI3IIE.py'
/usr/local/bin/python2.7 -O /tmp/tmpmI3IIE.py
  File "/usr/local/lib/python2.7/site-packages/txtorcon/controller_py3.py", line 13
    async def __aenter__(self):
            ^
SyntaxError: invalid syntax
```

Version: 18.3.0
OS: FreeBSD 11.2
Found in the FreeBSD port.

**Comment by meejah** [comment]
Can you describe how you get this error? Seems like possibly an issue with the FreeBSD ports, because "controller_py3.py" should only be imported from Python3.

**Comment by yurivict** [comment]
This error messages appear during the FreeBSD port build that runs with ```python-2.7```.

It runs the command ```python2.7 setup.py``` with environment variables set to install it into a particular prefix, etc.

**Comment by meejah** [comment]
Hmm, okay. I wonder if the Debian method of packaging txtorcon gives any hints to something I can provide in `setup.py` to help with this ... I don't know of any "standard" way of excluding files from source for "only Python3" or so.

**Comment by yurivict** [comment]
Package building succeeds even after these errors are printed.

**Comment by meejah** [comment]
Python 2 is officially EOL now anyway, and this doesn't apparently prevent building.
