### ISSUE TITLE
Add cryptography to requirements

### ISSUE THREAD

**Issue by llchan** [meejah/txtorcon#334]
I believe cryptography is required to import txtorcon, so it should be added to requirements.txt

**Comment by meejah** [comment]
Yes, true, the semi-recent `onion.py` stuff does import things from `cryptography`. This is already a dependency "by accident" because of Twisted, but it should be explicit yes.

**Comment by glowatsk** [comment]
Cryptography is in requirements.txt explicitly, this should no be closed.

**Comment by meejah** [comment]
Yes, thanks!
