### ISSUE TITLE
Use collections.abc instead of collections

### ISSUE THREAD

**Issue by MeggyCal** [meejah/txtorcon#336]
When I build txtorcon, following warning pops up:

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working

Python 3.8 will be changing its way to handle imports and it will not be able to import Abstract Base Classes (https://docs.python.org/3/library/collections.abc.html) from collections anymore.

Affected files:
txtorcon/controller.py: from collections import Sequence
txtorcon/torstate.py: import collections (you use only the Callable module, which is ABC)

**Comment by glowatsk** [comment]
Resolved as per https://github.com/meejah/txtorcon/commit/cc7ed186ab2a27b7399331d2f883bf3a7a680181

**Comment by meejah** [comment]
p.s. @glowatsk if you wanted to add a release-note comment that's always welcome in PRs too :)

**Comment by glowatsk** [comment]
@meejah I will update that too. Going to do some more tickets in here as well.
