### ISSUE TITLE
Drop or declare dependency on six

### ISSUE THREAD

**Issue by dvzrv** [meejah/txtorcon#395]
Hi! :wave: 

I am currently looking into the package on Arch Linux for this project.

I noticed that a few corners in the code exists, where six is being used.
As this project only targets Python > 3 it would probably be great to remove this (implicit dependency).

In the meantime it might be good to specify six as a dependency, as it is only pulled in implicitly via automat (and if that ever changes, downstreams will be broken).

**Comment by dvzrv** [comment]
Looking at the automat upstream, they do not in fact rely on six anymore and our packaging just does not yet reflect that.

**Comment by meejah** [comment]
Yes, and `six` usage can / should be dropped in txtorcon ... would accept a PR (or can hopefully do that myself later this week)

**Comment by a-detiste** [comment]
done
