### ISSUE TITLE
Can we allow passing our own socket server ?

### ISSUE THREAD

**Issue by thecockatiel** [meejah/txtorcon#402]
https://github.com/meejah/txtorcon/blob/1e6f661eb24934f24608790be56dfc2419811d7b/txtorcon/endpoints.py#L558-L564

I'm trying to get this to work with passing my own socket server, but due to the referenced code I don't think it's possible right now
it would be nice if we could

**Comment by meejah** [comment]
Sure. Can you say more about the exact usecase, and an API that would work for you?

**Comment by meejah** [comment]
Perhaps an (optional) `listen_endpoint=None` argument when creating the `TCPHiddenServiceEndpoint` instance?

(Unfortunately, such an arg can't be on the `listen()`  call since that's specified by the Twisted interface).

**Comment by thecockatiel** [comment]
Hey
Thanks for the swift response
I think I got it working by using `FilesystemOnionService.create` directly and passing my socket server IP and port

my use case is to do p2p messaging using sockets and protobuf, but all examples were using a web server, so it was a little hard to wrap my head around it

thanks for making this awesome library!
