### ISSUE TITLE
use signal/names to bootstrap valid signal list

### ISSUE THREAD

**Issue by meejah** [meejah/txtorcon#58]
Now that "signal/names" is available, use this instead of a static list to know what valid signals there are.

**Comment by araignee** [comment]
For reference, I found [info about the signal/names command] (https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n706) in the Tor control-spec. So, I think I need to use the getinfo signal/names to populate [`TorControlProtocol._bootstrap.valid_signals`] (https://github.com/meejah/txtorcon/blob/e41f9486db1a088ee7b79f914d56d6c372d914e6/txtorcon/torcontrolprotocol.py#L724)?

**Comment by meejah** [comment]
Yes, exactly, sometime during ``bootstrap()``

**Comment by meejah** [comment]
already implemented.
