### ISSUE TITLE
De-duplicate hidden-services by HiddenServiceDir

### ISSUE THREAD

**Issue by meejah** [meejah/txtorcon#89]
It turns out that Tor currently only "warns" if you have two hidden services that have the very same HiddenServiceDir.

So TorConfig should verify that we don't have two HiddenService instances pointing at the same directory, or tor will accept it with a warn, but one of them won't work at all.

**Comment by sammyshj** [comment]
There are 2 instances of adding the HiddenService once at https://github.com/sammyshj/txtorcon/blob/master/txtorcon/torconfig.py#L1113 and the other time at https://github.com/sammyshj/txtorcon/blob/master/txtorcon/torconfig.py#L1140. This means that when 2 HiddenServiceDir's are specified, the same directory gets appended twice. Does this look like the reason why the bug was encountered?

**Comment by meejah** [comment]
Oh, interesting. That certainly looks like a bug.
Can you write a test for this that fails?

We should also cover the case where a user of this code adds two hidden-services with the same directory.

**Comment by meejah** [comment]
Actually, the reason it's checking is that the first time we see HiddenServiceDir, it'll be None.

So, if there's precisely 1 HiddenServiceDir line, only the 1140 case gets hit; if there's 2, then 1113 gets called once, and 1140 once.

This bug is about what happens if a user of TorConfig adds two HiddenService instances with the same dir -- we shouldn't allow the second one to be added.

**Comment by sammyshj** [comment]
Hello @meejah ,
Currently in the _setup_hidden_services method, the HiddenService is being appended at two places. Will it be better to just have one instance of appending the HiddenService with the specific ports, ver, auth, group_read and directory? This way, the code will be easier to read.

**Comment by meejah** [comment]
Yeah if you can write it to be simpler, that'd be great.

It's really a state-machine, so it might even be better to use the state-machine code in ``spaghetti.FSM`` but that might not be more-clear ;) See how the ``client_keys`` are now parsed for an example of that and decide for yourself ;)

Bear in mind that the HiddenSevice stuff is order-based, and can have a variable number of lines for each hidden service -- when you see the  next ``HiddenServiceDir`` line, that begins a new hidden service (and there's no end marker).
