### ISSUE TITLE
add stealth authentication token option to hidden service endpoint parser

### ISSUE THREAD

**Issue by david415** [meejah/txtorcon#94]
I think many applications could benefit from using txtorcon hidden service endpoint descriptor strings that use stealth authentication tokens. Obviously this could be done by manipulating the filesystem... but it would be really great if we could do this all via the Tor control port. I'm not sure if that is possible without a feature addition to tor.

**Comment by meejah** [comment]
Except via using /dev/shm files, it would need tor support to do it without filesystem manipulation.

However, txtorcon also lacks support for using stealth authentication with hidden-services even as tor implements it today -- and this would be a great feature addition.

torconfig.HiddenService does take an auth= kwarg, but I don't believe it's implemented correctly anyway, so if necessary breaking that API is fine, IMO.

**Comment by meejah** [comment]
See #96 also.

This would need to use TorConfig to edit the ``HidServAuth`` setup of the Tor that it connected to...
(SETCONF alone won't work, because that will nuke any other ones the user had set up).

**Comment by meejah** [comment]
Once this is implemented for both servers and clients, it would be neat to add support in ``carml pastebin`` to actually use it. 

See https://github.com/meejah/carml/issues/2

**Comment by meejah** [comment]
this works
