### ISSUE TITLE
add Tor client endpoint and parser

### ISSUE THREAD

**Issue by david415** [meejah/txtorcon#95]
Meejah and I are currently working on creating a proper Tor client endpoint and parser. We had some additional features to add to the txtorsocksx implementation I wrote a while back... anyhow the branch of txtorcon that has this code is here:
https://github.com/david415/txtorcon/commits/tor-client-endpoint

I'd suggest we make it possible to use stealth hidden services with this Tor client endpoint... Should I open a separate ticket for that?

**Comment by meejah** [comment]
Yeah, I think a separate ticket is correct because txtorcon doesn't support stealth auth properly by itself yet. So, first support stealth auth, then support it via endpoints.

**Comment by meejah** [comment]
See branch tor-client-endpoint

**Comment by david415** [comment]
meejah merged my code (with some fixes) to trunk a while ago... so it's resolved!
